name: CITATION.cff

on:
  pull_request:
    paths:
      - CITATION.cff
      - .github/workflows/cff-validator.yml
  push:
    branches:
      - main
    paths:
      - CITATION.cff
      - .github/workflows/cff-validator.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    name: Validate CITATION.cff
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5.5.0
        with:
          persist-credentials: false

      - name: Validate CITATION.cff
        uses: dieghernan/cff-validator@d8f85828214016ce6976e740b6e0504c0fdc4dbb # v5
